server:
  port: 8899

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/otel-test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  application:
    name: simple-todo

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
    root: debug
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

micrometer:
  observations:
    annotations:
      enabled: true